language: python
python:
- '2.7'
cache: pip
install:
- pip install -r requirements.txt
script: cd airflow_scripts/dags/dependencies/dataflow_scripts && python -m unittest
  discover tests
git:
  quiet: true
before_install:
- openssl aes-256-cbc -K $encrypted_40a5ae8797b4_key -iv $encrypted_40a5ae8797b4_iv
  -in data_rivers_key.json.enc -out data_rivers_key.json -d
